name: example-firefox
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:

  firefox:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Firefox
        uses: ./
        timeout-minutes: 10080
        with:
          # let's show browser and system info
          build: npx cypress info
          working-directory: examples/browser
          browser: firefox

      # report screenshot size and store the screenshots as test artifacts
      - name: running browser
        run: cypress run --browser firefox
        shell: bash
        
      - uses: actions/upload-artifact@v4
        with:
          name: screenshots-in-firefox
          path: examples/browser/cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/browser

      - name: Sleep
        run: sleep 1d
        shell: bash
