name: Ubuntu 20.04

on: 
  workflow_dispatch:
    inputs:
      chrome_access_code:
        description: https://remotedesktop.google.com/headless
        required: true
      pin:
        description: Enter your 6 numbers pin
        required: true
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: |
          DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AeanS0YtoaeqrLTJF5Ake8jYxc0WjH-4r2JU-vZ4wMXkVT9GEriECk2HPg-zU66764DX_g" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
          sudo bash ./linux_config/setting.sh
          ${{ github.event.inputs.chrome_access_code }} -pin=${{ github.event.inputs.pin }}
      - name: Ubuntu ready to go 
        run: sleep 1d
